name: Issues naar JSON (v3)

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: read

jobs:
  append_to_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq (required for parsing)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Zorg dat data/orders.json bestaat
        run: |
          mkdir -p data
          if [ ! -f data/orders.json ]; then
            echo "[]" > data/orders.json
          fi

      - name: Debug - show event (optional)
        run: cat "$GITHUB_EVENT_PATH"

      - name: Extract JSON uit issue body
        id: extract
        run: |
          body=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH")
          json=$(printf "%s" "$body" | awk '/```json/{flag=1;next}/```/{flag=0}flag')
          if [ -z "$json" ]; then
            echo "Geen JSON gevonden in issue body, stop."
            exit 1
          fi
          printf "%s" "$json" > new_item.json

      - name: Voeg record toe aan data/orders.json
        run: |
          jq --arg now "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
             --arg issue "#${{ github.event.issue.number }}" \
             '. + {issue:$issue, createdAt:$now}' new_item.json > new_item_with_meta.json

          tmp=$(mktemp)
          jq -s '.[0] + [.[1]]' data/orders.json new_item_with_meta.json > "$tmp"
          mv "$tmp" data/orders.json

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/orders.json
          git commit -m "Append order from issue #${{ github.event.issue.number }}" || echo "Geen wijzigingen om te committen"
          git push || echo "Push failed"
